import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ErrorBoundary } from "@/modules/errorBoundary";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ErrorBoundary fallback={<div>Something went wrong</div>}> */}
        <NextTopLoader
          color="red"
          zIndex={100000}
          showSpinner={false}
          crawlSpeed={200}
          crawl={true}
          height={3}
        />
        {children}
        {/* </ErrorBoundary> */}
      </body>
    </html>
  );
}
